apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
data:
  server.insecure: "true"
  server.rootpath: "/argocd"
  server.grpc.web: "true"
  application.instanceLabelKey: "argocd.argoproj.io/instance"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: "http://argo.tail732e1e.ts.net/argocd"
  application.instanceLabelKey: "argocd.argoproj.io/instance"
  server.rbac.log.enforce.enable: "false"
  exec.enabled: "false"
  admin.enabled: "true"
  timeout.reconciliation: "180s"
  timeout.hard.reconciliation: "0s"