apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webbion-web-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: argo.tail732e1e.ts.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webbion-web-app-service
                port:
                  number: 80
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webbion-web-app-service
                port:
                  number: 80