apiVersion: apps/v1
kind: Deployment
metadata:
  name: webbion-web-app
  labels:
    app: webbion-web-app
  annotations:
    argocd-image-updater.argoproj.io/image-list: webbion=ghcr.io/gregmortenoliver/webbion
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webbion-web-app
  template:
    metadata:
      labels:
        app: webbion-web-app
    spec:
      containers:
        - name: webbion-web-app
          image: ghcr.io/gregmortenoliver/webbion:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
      imagePullSecrets:
        - name: boliver
