apiVersion: apps/v1
kind: Deployment
metadata:
  name: webbion-web-app
  labels:
    app: webbion-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webbion-web-app
  template:
    metadata:
      labels:
        app: webbion-web-app
    spec:
      containers:
        - name: webbion-web-app
          image: ghcr.io/gregmortenoliver/webbion:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
      imagePullSecrets:
        - name: boliver
      env:
        - name: PUBLIC_AUTH0_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: auth0
              key: PUBLIC_AUTH0_CLIENT_ID
              
        - name: PUBLIC_AUTH0_DOMAIN
          valueFrom:
            secretKeyRef:
              name: auth0
              key: PUBLIC_AUTH0_DOMAIN

        - name: PUBLIC_AUTH0_AUDIENCE
          valueFrom:
            secretKeyRef:
              name: auth0
              key: PUBLIC_AUTH0_AUDIENCE

        - name: PUBLIC_AUTH0_CALLBACK_URL
          valueFrom:
            secretKeyRef:
              name: auth0
              key: PUBLIC_AUTH0_CALLBACK_URL

