apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: gateway-deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
