apiVersion: v1
kind: Service
metadata:
  name: booking-service-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: booking-service-deployment
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004
