apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: org-mongo-statefulset
spec:
  # serviceName is removed - not needed for a standalone instance.
  replicas: 1
  selector:
    matchLabels:
      app: org-mongo
  template:
    metadata:
      labels:
        app: org-mongo
    spec:
      containers:
        - name: org-mongo
          image: mongo:latest
          # --- SIMPLIFIED COMMAND ---
          command:
            - "mongod"
            - "--bind_ip_all"
            # --auth enables username/password security.
            - "--auth"
          ports:
            - containerPort: 27017
          envFrom:
            - secretRef:
                name: org-mongo-secret
          volumeMounts:
            - name: org-mongo-persistent-storage
              mountPath: /data/db
      # No keyfile volume needed anymore.
  volumeClaimTemplates:
    - metadata:
        name: org-mongo-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
