apiVersion: v1
kind: Service
metadata:
  name: user-service-service
  namespace: default
spec:
  selector:
    app: user-service-deployment
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
